QuanLyBanHangCSharpMVC/Areas/Admin/Controllers/StatisticalController.cs
using Models.DAO;
using System;
using System.Threading.Tasks;
using System.Web.Helpers;
using System.Web.Mvc;

namespace QuanLyBanHangCSharpMVC.Areas.Admin.Controllers
{
    public class StatisticalController : BaseController
    {
        private readonly StatisticalDAO statisticalDAO = new StatisticalDAO();
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult StatisticalBill(int? year)
        {
            var totalPrice = statisticalDAO.GetTotalPriceByYear(year ?? DateTime.Now.Year);
            return Json(totalPrice);
        }
    }
}

QuanLyBanHangCSharpMVC/Areas/Admin/Views/Statistical/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section JsSection {
    <script>
        $(document).ready(function () {
            $.ajax({
                method: "Post",
                url: "@Url.Action("StatisticalBill", "Statistical")",
                data: { year: new Date().getUTCFullYear() },
                success: function (result) {
                    let data = [];
                    for (let i = 0; i < result.length; ++i) {
                        let item = result[i];
                        let p = {
                            x: item.Month,
                            y: item.TotalPrice
                        };
                        data.push(p);
                    }
                    var chart = new CanvasJS.Chart("chartContainer", {       
						animationEnabled: true,
                        axisX: {
							title: "Tháng",
							minimum: 0,
                            maximum: 12
                        },
						axisY: {
							title: "Tổng tiền",
		                    suffix: " VND"
						},
						data: [{
                            type: "column",
                            dataPoints: data
						}]
					});
					chart.render();

					var xSnapDistance = chart.axisX[0].convertPixelToValue(chart.get("dataPointWidth")) / 2;
					var ySnapDistance = 3;

					var xValue, yValue;

					var mouseDown = false;
					var selected = null;
					var changeCursor = false;

					var timerId = null;

					function getPosition(e) {
						var parentOffset = $("#chartContainer > .canvasjs-chart-container").offset();          	
						var relX = e.pageX - parentOffset.left;
						var relY = e.pageY - parentOffset.top;
						xValue = Math.round(chart.axisX[0].convertPixelToValue(relX));
                        yValue = Math.round(chart.axisY[0].convertPixelToValue(relY));
					}

					function searchDataPoint() {
                        var dps = chart.data[0].dataPoints;
						for(var i = 0; i < dps.length; i++ ) {
							if( (xValue >= dps[i].x - xSnapDistance && xValue <= dps[i].x + xSnapDistance) && (yValue >= dps[i].y - ySnapDistance && yValue <= dps[i].y + ySnapDistance) ) 
							{
								if(mouseDown) {
                                    selected = i;	
									break;
								} else {
									changeCursor = true;
									break; 
								}
							} else {
								selected = null;
								changeCursor = false;
							}
						}
					}

					jQuery("#chartContainer > .canvasjs-chart-container").on({
						mousedown: function(e) {
							mouseDown = true;
							getPosition(e);  
							searchDataPoint();
						},
						mousemove: function(e) {
							getPosition(e);
							if(mouseDown) {
								clearTimeout(timerId);
								timerId = setTimeout(function(){
									if(selected != null) {
										chart.data[0].dataPoints[selected].y = yValue;
										chart.render();
									}   
								}, 0);
							}
							else {
								searchDataPoint();
								if(changeCursor) {
									chart.data[0].set("cursor", "n-resize");
								} else {
									chart.data[0].set("cursor", "default");
								}
							}
						},
						mouseup: function(e) {
							if(selected != null) {
								chart.data[0].dataPoints[selected].y = yValue;
								chart.render();
								mouseDown = false;
							}
						}
					});
                }
            })
        });
    </script>
}

<div style="text-align: center;"><h1>Thống kê tiền bán hàng</h1></div>
<div id="chartContainer" style="height: 370px; width: 100%;"></div>