QuanLyBanHangCSharpMVC/Controllers/CartController.cs
using Models.DAO;
using Models.EntityFrameworkCore;
using QuanLyBanHangCSharpMVC.Helpers;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace QuanLyBanHangCSharpMVC.Controllers
{
    public class CartController : BaseController
    {
        private ProductDAO productDAO = new ProductDAO();
        private CartDAO cardDAO = new CartDAO();
        private BillDAO billDAO = new BillDAO();
        [HttpGet]
        public async Task<ActionResult> Index(long id)
        {
            var cards = await cardDAO.GetAllCartByAccount(id);
            ViewBag.ToTal = cards.Sum(x => x.QuantityPurchased);
            ViewBag.TotalPrice = cards.Sum(x => x.Price);
            return View(cards);
        }

        [HttpPost]
        public async Task<ActionResult> Create(long productId)
        {
            var accountId = ((Account)Session[Constant.UserCustomerSession]).Id;
            var product = await productDAO.GetProductById(productId);
            var cart = new Cart
            {
                AccountId = accountId,
                ProductId = productId,
                Price = product.Price,
                QuantityPurchased = 1
            };
            int result = await cardDAO.CreateCart(cart);
            if (result > 0)
                TempData["SaveCart"] = "Thêm sản phẩm vào giỏ hàng thành công!";
            return Json(result);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(long id, long productId, long quantity)
        {
            var product = await productDAO.GetProductById(productId);
            int result = await cardDAO.EditCart(id, quantity, product.Price);
            if (result > 0)
                TempData["SaveCart"] = "Cập nhật số lượng thành công!";
            return Json(result);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(long id)
        {
            int result = await cardDAO.DeleteCart(id);
            if (result > 0)
                TempData["DeleteCart"] = "Xóa sản phẩm thành công!";
            return Json(result);
        }

        [HttpPost]
        public async Task<ActionResult> Order()
        {
            var account = (Account)Session[Constant.UserCustomerSession];
            var productOrders = await cardDAO.GetAllProductOrder(account.Id);
            if (productOrders == null)
                return Json(0);
            long totalPrice = productOrders.Sum(x => x.Price * x.QuantityPurchased);
            var bill = new Bill
            {
                Address = account.User.Address,
                CreationTime = DateTime.Now,
                BillStatus = BillStatus.AwaitingApproval,
                TotalPrice = totalPrice,
                VAT = (long)(totalPrice * 0.1),
                AccountId = account.Id
            };
            bill.Id = await billDAO.CreateBill(bill);
            var billInfos = productOrders.Select(x => new BillInfo
            {
                BillId = bill.Id,
                Price = x.Price,
                ProductId = x.ProductId,
                QuantityPurchased = x.QuantityPurchased
            }).ToList();
            int res = await billDAO.CreateBillInfo(billInfos);
            if (res > 0)
                TempData["Order"] = "Đơn hàng đã được thành công!";
            return Json(res);
        }
    }
}

QuanLyBanHangCSharpMVC/Controllers/ProductController.cs
using Models.DAO;
using QuanLyBanHangCSharpMVC.Helpers;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace QuanLyBanHangCSharpMVC.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductDAO productDAO = new ProductDAO();
        [HttpGet]
        public async Task<ActionResult> Index(long id)
        {
            var product = await productDAO.GetProductByIdAndRelated(id);
            if (product == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(product);
        }

        [HttpGet]
        public ActionResult GetProductByKeyword(string search)
        {
            var products = productDAO.GetAllProductImageByKeyWord(search);
            return View(products);
        }
    }
}

QuanLyBanHangCSharpMVC/Controllers/RegisterController.cs
using Models.DAO;
using Models.DTO;
using Models.EntityFrameworkCore;
using QuanLyBanHangCSharpMVC.Areas.Admin.Data;
using QuanLyBanHangCSharpMVC.Helpers;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace QuanLyBanHangCSharpMVC.Controllers
{
    public class RegisterController : Controller
    {
        private AccountDAO accountDAO = new AccountDAO();
        private UserDAO userDAO = new UserDAO();
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(UserDto userDto)
        {
            bool checkEmail = await accountDAO.CheckEmailExistAsync(userDto.Email);
            if (!checkEmail)
            {
                User user = new User
                {
                    Address = userDto.Address,
                    Name = userDto.Name,
                    Phone = userDto.Phone,
                    UserSatus = UserSatus.Active
                };
                long userId = await userDAO.CreateUserAsync(user);
                userDto.Password = PasswordMd5.HashPassword(userDto.Password);
                Account account = new Account
                {
                    AccountRole = AccountRole.User,
                    Email = userDto.Email,
                    Password = userDto.Password,
                    UserId = userId,
                    AccountStatus = AccountStatus.Active
                };
                bool result = await accountDAO.CreateAccountAsync(account);
                if (result)
                {
                    TempData["AddAcountSuccess"] = "Đăng ký tài khoản thành công!";
                    return RedirectToAction("Index", "Login");
                }
                else
                    ModelState.AddModelError("AddUserFail", "Đăng ký không thành công!");
            }
            else
                ModelState.AddModelError("EmailExits", "Email đã tồn tại!");
            return View(userDto);
        }

        [HttpGet]
        public ActionResult Edit()
        {

            var account = (Account)Session[Constant.UserCustomerSession];
            if (account == null)
                return RedirectToAction("Index", "Login");
            AccountUserDto user = new AccountUserDto
            {
                Address = account.User.Address,
                Email = account.Email,
                Name = account.User.Name,
                Phone = account.User.Phone,
                Id = account.UserId
            };
            return View(user);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(AccountUserDto userDto)
        {
            if(!string.IsNullOrWhiteSpace(userDto.NewPassword))
                userDto.Password = PasswordMd5.HashPassword(userDto.NewPassword);
            bool result = await userDAO.EditAsync(userDto);
            if (result)
                TempData["EditAccount"] = "Cập nhật thông tin thành công!";
            else
                TempData["EditAccount"] = "Đã hủy cập nhật thông tin!";
            return RedirectToAction("Index", "Home");
        }
    }
}

QuanLyBanHangCSharpMVC/Views/Shared/_Layout.cshtml
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <title>New Store A Ecommerce Category Flat Bootstarp Resposive Website Template | Home :: w3layouts</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <!-- Custom Theme files -->
    <!--theme-style-->
    <link href="~/Content/Site/css/style.css" rel="stylesheet" />
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <!--//theme-style-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="New Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- start menu -->
    <link href="~/Content/Site/css/memenu.css" rel="stylesheet" />
    <script src="~/Content/Site/js/memenu.js"></script>
    <script>$(document).ready(function () { $(".memenu").memenu(); });</script>
    <script src="~/Content/Site/js/simpleCart.min.js"></script>
</head>
<body>
    <!--header-->
    <div class="header">
        <div class="header-top">
            <div class="container">
                <div class="search">
                    @using (Html.BeginForm("GetProductByKeyword", "Product", FormMethod.Get))
                    {
                        <input type="text" name="search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Tìm kiếm';}">
                        <input type="submit" value="Go">
                    }
                </div>
                <div class="header-left">
                    @{ var account = (Account)Session[Constant.UserCustomerSession]; }
                    <ul>
                        @if (account == null)
                        {
                            <li><a href="@Url.Action("Index", "Login")">Login</a></li>
                            <li><a href="@Url.Action("Index", "Register")">Register</a></li>
                        }
                        else
                        {
                            <li><a href="@Url.Action("Edit", "Register")">@account.User.Name</a></li>
                            <li><a href="@Url.Action("Logout", "Login")">Logout</a></li>
                        }
                    </ul>
                    @if (account != null)
                    {
                        <div class="cart box_1">
                            <a href="@Url.Action("Index", "Cart", new { id = account.Id })">
                                <h3><img src="~/Content/Site/images/cart.png" /></h3>
                            </a>
                        </div>
                    }
                    <div class="clearfix"> </div>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
        <div class="container">
            <div class="head-top">
                <div class="logo">
                    <a href="/">
                        <img width="165" height="50" style="object-fit: contain;" src="~/Content/Site/images/logo.jpg" />
                    </a>
                </div>
                <div class=" h_menu4">
                    <ul class="memenu skyblue">
                        <li class="active grid"><a class="color8" href="@Url.Action("Index", "Home")">Home</a></li>
                        @Html.Action("MenuPartial", "Home")
                        <li><a class="color4" href="#">Blog</a></li>
                        <li><a class="color6" href="#">Conact</a></li>
                    </ul>
                </div>

                <div class="clearfix"> </div>
            </div>
        </div>

    </div>
    @RenderBody()
    <div class="footer" style="margin-top: 20px;">
        <div class="container">
            <div class="footer-top-at">

                <div class="col-md-4 amet-sed">
                    <h4>MORE INFO</h4>
                    <ul class="nav-bottom">
                        <li><a href="#">How to order</a></li>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Location</a></li>
                        <li><a href="#">Shipping</a></li>
                        <li><a href="#">Membership</a></li>
                    </ul>
                </div>
                <div class="col-md-4 amet-sed ">
                    <h4>CONTACT US</h4>

                    <p>
                        Contrary to popular belief
                    </p>
                    <p>The standard chunk</p>
                    <p>office:  +84354540505</p>
                    <ul class="social">
                        <li><a href="#"><i> </i></a></li>
                        <li><a href="#"><i class="twitter"> </i></a></li>
                        <li><a href="#"><i class="rss"> </i></a></li>
                        <li><a href="#"><i class="gmail"> </i></a></li>

                    </ul>
                </div>
                <div class="col-md-4 amet-sed">
                    <h4>Newsletter</h4>
                    <p>
                        Sign Up to get all news update
                        and promo
                    </p>
                    <form>
                        <input type="text" value="" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='';}">
                        <input type="submit" value="Sign up">
                    </form>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
        <div class="footer-class">
            <p>© 2020 New store All Rights Reserved | Design by  <a href="#">Nguyễn Văn Tùng</a> </p>
        </div>
    </div>
    @Scripts.Render("~/bundles/toastr")
    @RenderSection("JsSection", false)
</body>
</html>