QuanLyBanHangCSharpMVC/Areas/Admin/Controllers/HomeController.cs
using System.Web.Mvc;

namespace QuanLyBanHangCSharpMVC.Areas.Admin.Controllers
{
    public class HomeController : BaseController
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

QuanLyBanHangCSharpMVC/Controllers/CategoryController.cs
using Models.DAO;
using QuanLyBanHangCSharpMVC.Helpers;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace QuanLyBanHangCSharpMVC.Controllers
{
    public class CategoryController : Controller
    {
        private ProductDAO productDAO = new ProductDAO();
        [HttpGet]
        public async Task<ActionResult> Index(long id, int pageSize = 9, int currentPage = 1)
        {
            var products = await productDAO.GetAllProductByCategory(id, pageSize, currentPage);
            ViewBag.PageNumber = Paginate.GetTotalPage(products.TotalCount, pageSize);
            ViewBag.CategoryId = id;
            return View(products.Items);
        }

        public async Task<ActionResult> CategoryPartial(long id, int currentPage = 1, int pageSize = 9)
        {
            var products = await productDAO.GetAllProductByCategory(id, pageSize, currentPage);
            ViewBag.PageNumber = Paginate.GetTotalPage(products.TotalCount, pageSize);
            return PartialView(products.Items);
        }
    }
}

QuanLyBanHangCSharpMVC/Controllers/HomeController.cs
using Models.DAO;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace QuanLyBanHangCSharpMVC.Controllers
{
    public class HomeController : Controller
    {
        private CategoryDAO categoryDAO = new CategoryDAO();
        private ProductDAO productDAO = new ProductDAO();
        private ProducerDAO producerDAO = new ProducerDAO();
        public async Task<ActionResult> Index()
        {
            return await Task.Run(() =>
            {
                return View();
            });
        }

        [ChildActionOnly]
        public ActionResult MenuPartial()
        {
            var category = categoryDAO.GetAllCategoryActive();
            return PartialView(category);
        }

        [ChildActionOnly]
        public ActionResult MenuLeftPartial()
        {
            var categories = categoryDAO.GetAllCategoryActive();
            var newProducts = productDAO.GetNewProducts();
            ViewBag.Products = newProducts;
            return PartialView(categories);
        }

        [ChildActionOnly]
        public ActionResult ProducerPartial()
        {
            var producer = producerDAO.GetAllProducerActive();
            return PartialView(producer);
        }

        [ChildActionOnly]
        public ActionResult NewProductPartial()
        {
            var products = productDAO.GetNewProducts(12);
            return PartialView(products);
        }
    }
}

QuanLyBanHangCSharpMVC/Controllers/ProducerController.cs
using Models.DAO;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace QuanLyBanHangCSharpMVC.Controllers
{
    public class ProducerController : Controller
    {
        private ProducerDAO producerDAO = new ProducerDAO();
        [HttpGet]
        public async Task<ActionResult> Index(long id, int currentPage = 1, int pageSize = 9)
        {
            var products = await producerDAO.GetAllProductByProducerAsync(id, currentPage, pageSize);
            return View(products);
        }
    }
}

QuanLyBanHangCSharpMVC/Controllers/ProductController.cs
using Models.DAO;
using QuanLyBanHangCSharpMVC.Helpers;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace QuanLyBanHangCSharpMVC.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductDAO productDAO = new ProductDAO();
        [HttpGet]
        public async Task<ActionResult> Index(long id)
        {
            var product = await productDAO.GetProductByIdAndRelated(id);
            if (product == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(product);
        }

        [HttpGet]
        public ActionResult GetProductByKeyword(string search)
        {
            var products = productDAO.GetAllProductImageByKeyWord(search);
            return View(products);
        }
    }
}

QuanLyBanHangCSharpMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section JsSection {
    <script type="text/javascript">
         $(document).ready(function() {
            if('@TempData["EditAccount"]')
            {
                toastr.success('@TempData["EditAccount"]');
                @{ TempData["EditAccount"] = ""; }
            }
        });
    </script>
}
<!--content-->
<div class="content">
    <div class="container">
        <div class="content-top">
            <h1>Sản phẩm mới</h1>
            @Html.Action("NewProductPartial", "Home")
        </div>
    </div>
    <div style="text-align: center;"><h3><b>Danh sách hãng sản xuất</b></h3></div>
    @Html.Action("ProducerPartial", "Home")
</div>

QuanLyBanHangCSharpMVC/Views/Home/MenuLeftPartial.cshtml
@model List<Category>
<div class="col-md-3 product-price">
    <div class=" rsidebar span_1_of_left">
        <div class="of-left">
            <h3 class="cate">Danh mục</h3>
        </div>
        <ul class="row menu-category">
            @foreach (var item in Model)
            {
                <a href="@Url.Action("Index", "Category", new { id = item.Id })">
                    <li class="col-sm-12 item1">
                        <div class="col-sm-4"></div>
                        @item.Name
                    </li>
                </a>
            }
        </ul>
    </div>
    <!--initiate accordion-->
    <script type="text/javascript">
        $(function () {
            var menu_ul = $('.menu > li > ul'),
                menu_a = $('.menu > li > a');
            menu_ul.hide();
            menu_a.click(function (e) {
                e.preventDefault();
                if (!$(this).hasClass('active')) {
                    menu_a.removeClass('active');
                    menu_ul.filter(':visible').slideUp('normal');
                    $(this).addClass('active').next().stop(true, true).slideDown('normal');
                } else {
                    $(this).removeClass('active');
                    $(this).next().stop(true, true).slideUp('normal');
                }
            });

        });
    </script>
    <div class="product-bottom">
        <div class="of-left-in">
            <h3 class="best">Sản phẩm mới</h3>
        </div>
        @{ var products = (List<ProductModel>)ViewBag.Products; }
        @{ CultureInfo cul = CultureInfo.GetCultureInfo("vi-VN"); }
        @foreach (var item in products)
        {
            <div class="product-go">
                <div class=" fashion-grid">
                    <a href="@Url.Action("Index", "Product", new { id = item.Id })"><img class="img-responsive " src="@item.Image.Path" alt=""></a>
                </div>
                <div class=" fashion-grid1">
                    <h6 class="best2">
                        <a href="@Url.Action("Index", "Product", new { id = item.Id })">@item.Name</a>
                    </h6>
                    <span class=" price-in1">@item.Price.ToString("#,###", cul.NumberFormat) VND</span>
                </div>

                <div class="clearfix"> </div>
            </div>
        }
    </div>
</div>
<style>
    .menu-category {
        width: auto;
        height: auto;
        padding: 0;
        list-style: none;
        margin-bottom: 10px;
        border: 1px solid #e3e3e3;
    }

    .menu-category > a li {
        width: 100%;
        font-size: 1.3em;
        padding-bottom: 5px;
        padding-top: 5px;
        cursor: pointer;
    }

    .menu-category > a li {
        color: black;
    }

    .menu-category > a li:hover {
        background-color: gray;
        color: white;
    }
</style>

QuanLyBanHangCSharpMVC/Views/Home/MenuPartial.cshtml
@model List<Category>

@foreach (var item in Model)
{
    <li>
        <a class="color1" href="@Url.Action("Index", "Category", new { id = item.Id })">@item.Name</a>
    </li>
}

QuanLyBanHangCSharpMVC/Views/Home/NewProductPartial.cshtml
@model List<ProductModel>

<div class="grid-in row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 grid-top">
            <div style="min-height: 450px;">
                <a href="@Url.Action("Index", "Product", new { id = item.Id })" class="b-link-stripe b-animate-go thickbox">
                    <img style="min-height: 350px; min-width: 350px;" class="img-responsive" src="@item.Image.Path" alt="">
                    <div class="b-wrapper">
                        <h3 class="b-animate b-from-left b-delay03 ">
                            <span>@item.Name</span>
                        </h3>
                    </div>
                </a>
                <p><a href="@Url.Action("Index", "Product", new { id = item.Id })">@item.Name</a></p>
            </div>
        </div>
    }
    <div class="clearfix"> </div>
</div>

QuanLyBanHangCSharpMVC/Views/Home/ProducerPartial.cshtml
@model List<ProducerRequest>
<div class="content-bottom">
    <ul>
        @foreach (var item in Model)
        {
            <li><a href="@Url.Action("Index", "Producer", new { id = item.Id })"><img title="@item.Name" class="image-producer img-responsive" src="@item.Logo.Path" alt="@item.Name"></a></li>
        }
    </ul>
    <div class="clearfix"> </div>
</div>
<style>
    .image-producer {
        width: 80%;
        max-width: 80%;
        height: 100px;
        max-height: 100px;
    }
</style>